
zuul:
  #add-host-header: true #网关在进行请求路由转发前为请求设置Host头信息
  sensitiveHeaders: Session,Origin,Cookie,Set-Cookie,Authorization
  semaphore:
    max-semaphores: 5000
  routes:
    video-route:
      path: /gw/video-server/**
      serviceId: video-server
    user-route:
      path: /gw/user-server/**
      serviceId: user-server
error:
  path: /gw/error